"""baseline schema

Revision ID: b959448d5564
Revises: 
Create Date: 2026-06-06 23:20:21.432042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b959448d5564'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master',
    sa.Column('its', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('passport_number', sa.String(), nullable=False),
    sa.Column('passport_expiry', sa.Date(), nullable=False),
    sa.Column('visa_number', sa.String(), nullable=False),
    sa.Column('mode_of_transport', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('sim_issued', sa.Boolean(), nullable=False),
    sa.Column('arrived', sa.Boolean(), nullable=False),
    sa.Column('arrival_timestamp', sa.DateTime(), nullable=True),
    sa.Column('departed', sa.Boolean(), nullable=False),
    sa.Column('departure_timestamp', sa.DateTime(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('its'),
    sa.UniqueConstraint('passport_number'),
    sa.UniqueConstraint('visa_number')
    )
    with op.batch_alter_table('master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_its'), ['its'], unique=False)

    op.create_table('transport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('transport_type', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('booking_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('its', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('issued', sa.Boolean(), nullable=False),
    sa.Column('departed', sa.Boolean(), nullable=False),
    sa.Column('self_issued', sa.Boolean(), nullable=False),
    sa.Column('seat_number', sa.String(), nullable=True),
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.Column('coach_number', sa.String(), nullable=True),
    sa.Column('cabin_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('booking_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['its'], ['master.its'], ),
    sa.ForeignKeyConstraint(['transport_id'], ['transport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_info_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_info_its'), ['its'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_info_mode'), ['mode'], unique=False)

    op.create_table('bus',
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('bus_number', sa.Integer(), nullable=False),
    sa.Column('no_of_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('bus_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['transport.id'], ),
    sa.PrimaryKeyConstraint('bus_id'),
    sa.UniqueConstraint('bus_number')
    )
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bus_bus_type'), ['bus_type'], unique=False)

    op.create_table('plane',
    sa.Column('plane_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('no_of_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plane_id'], ['transport.id'], ),
    sa.PrimaryKeyConstraint('plane_id'),
    sa.UniqueConstraint('flight_number')
    )
    op.create_table('processed_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('its', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('passport_number', sa.String(), nullable=False),
    sa.Column('passport_expiry', sa.Date(), nullable=False),
    sa.Column('visa_number', sa.String(), nullable=False),
    sa.Column('mode_of_transport', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('arrived', sa.Boolean(), nullable=False),
    sa.Column('processed_timestamp', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('processed_by_username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['its'], ['master.its'], ),
    sa.ForeignKeyConstraint(['processed_by_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processed_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_master_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_master_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_master_its'), ['its'], unique=True)
        batch_op.create_index(batch_op.f('ix_processed_master_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_master_middle_name'), ['middle_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_master_mode_of_transport'), ['mode_of_transport'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_master_passport_expiry'), ['passport_expiry'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_master_passport_number'), ['passport_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_master_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_master_visa_number'), ['visa_number'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transport_id'], ['transport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_route'), ['route'], unique=False)

    op.create_table('train',
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('train_name', sa.String(), nullable=False),
    sa.Column('train_number', sa.String(), nullable=False),
    sa.Column('no_of_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['transport.id'], ),
    sa.PrimaryKeyConstraint('train_id'),
    sa.UniqueConstraint('train_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('train')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_route'))
        batch_op.drop_index(batch_op.f('ix_schedules_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('processed_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_master_visa_number'))
        batch_op.drop_index(batch_op.f('ix_processed_master_phone'))
        batch_op.drop_index(batch_op.f('ix_processed_master_passport_number'))
        batch_op.drop_index(batch_op.f('ix_processed_master_passport_expiry'))
        batch_op.drop_index(batch_op.f('ix_processed_master_mode_of_transport'))
        batch_op.drop_index(batch_op.f('ix_processed_master_middle_name'))
        batch_op.drop_index(batch_op.f('ix_processed_master_last_name'))
        batch_op.drop_index(batch_op.f('ix_processed_master_its'))
        batch_op.drop_index(batch_op.f('ix_processed_master_id'))
        batch_op.drop_index(batch_op.f('ix_processed_master_first_name'))

    op.drop_table('processed_master')
    op.drop_table('plane')
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bus_bus_type'))

    op.drop_table('bus')
    with op.batch_alter_table('booking_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_info_mode'))
        batch_op.drop_index(batch_op.f('ix_booking_info_its'))
        batch_op.drop_index(batch_op.f('ix_booking_info_id'))

    op.drop_table('booking_info')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('transport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_id'))

    op.drop_table('transport')
    with op.batch_alter_table('master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_its'))

    op.drop_table('master')
    # ### end Alembic commands ###
